'use client'

import DashboardLayout from '@/components/dashboard-layout'

const TABS = ['overview', 'usage', 'performance', 'health', 'caching', 'rate-limits', 'cost', 'logs', 'insights'] as const

function TabBar() {
  return (
    <div className="flex items-center gap-1 px-4 border-b overflow-x-auto no-scrollbar" style={{ borderColor: 'var(--color-kumo-line)', background: 'var(--color-kumo-canvas)' }}>
      {TABS.map(tab => {
        const href =
          tab === 'overview' ? '/dashboard/analytics' :
          tab === 'usage'    ? '/dashboard/analytics/usage' :
          `/dashboard/analytics/${tab}`
        const isActive = tab === 'insights'
        return (
          <a key={tab} href={href} className="relative px-3 py-2.5 text-sm font-medium no-underline transition-colors"
            style={{ color: isActive ? 'var(--text-color-kumo-default)' : 'var(--text-color-kumo-subtle)', borderBottom: isActive ? '2px solid var(--color-kumo-brand)' : '2px solid transparent', marginBottom: -1, whiteSpace: 'nowrap' }}>
            {tab === 'rate-limits' ? 'Rate limits' : tab.charAt(0).toUpperCase() + tab.slice(1)}
          </a>
        )
      })}
    </div>
  )
}

type Trend = 'up' | 'down' | 'neutral'
type Insight = { title: string; value: string; detail: string; trend: Trend; positive: boolean }

const INSIGHTS: Insight[] = [
  { title: 'Osmium AI usage increased',  value: '+42%',    detail: 'Compared to the previous 30-day period. Driven by a spike in /api/v1/messages traffic.',                  trend: 'up',      positive: true  },
  { title: 'Average latency improved',   value: '−18%',    detail: 'P50 dropped from 151 ms to 124 ms after the inference cluster optimization on Jul 24.',                   trend: 'down',    positive: true  },
  { title: 'RUX generated tokens',       value: '3.2 M',   detail: 'Total tokens generated by the RUX workspace this month — 12% above the monthly average.',                trend: 'up',      positive: true  },
  { title: 'Expected monthly spend',     value: '₹52,000', detail: 'Projected based on current daily burn rate. 8% higher than last month due to increased Osmium AI usage.', trend: 'neutral', positive: false },
  { title: 'Cache hit rate declined',    value: '−6 pp',   detail: 'Hit rate fell from 90% to 84% after a model version update invalidated cached prompt prefixes.',          trend: 'down',    positive: false },
  { title: 'Error rate near zero',       value: '0.41%',   detail: 'Lowest 30-day error rate on record. No 5xx errors in the last 72 hours.',                                 trend: 'down',    positive: true  },
]

const ArrowUp = () => (
  <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
    <path d="M6.5 10.5V2.5M2.5 6.5l4-4 4 4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
)
const ArrowDown = () => (
  <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
    <path d="M6.5 2.5v8M2.5 6.5l4 4 4-4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/>
  </svg>
)
const Minus = () => (
  <svg width="13" height="13" viewBox="0 0 13 13" fill="none">
    <path d="M2.5 6.5h8" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/>
  </svg>
)

function InsightCard({ insight }: { insight: Insight }) {
  const trendColor = insight.trend === 'neutral'
    ? 'var(--text-color-kumo-subtle)'
    : insight.positive
      ? 'var(--text-color-kumo-default)'
      : 'var(--text-color-kumo-subtle)'

  const TrendIcon = insight.trend === 'up' ? ArrowUp : insight.trend === 'down' ? ArrowDown : Minus

  return (
    <div style={{
      background: 'var(--color-kumo-base)',
      border: '1px solid var(--color-kumo-line)',
      borderRadius: 10,
      padding: 'clamp(0.875rem,3vw,1.25rem)',
      display: 'flex',
      flexDirection: 'column',
      gap: 14,
    }}>
      {/* title row */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
        <span style={{ fontSize: 13, color: 'var(--text-color-kumo-subtle)', lineHeight: 1.4 }}>
          {insight.title}
        </span>
        <span style={{
          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
          width: 24, height: 24, borderRadius: 6, flexShrink: 0,
          background: 'var(--color-kumo-tint)',
          color: 'var(--text-color-kumo-subtle)',
        }}>
          <TrendIcon />
        </span>
      </div>

      {/* value */}
      <div style={{
        fontSize: 'clamp(1.375rem,5vw,1.875rem)',
        fontWeight: 500,
        letterSpacing: '-0.03em',
        fontVariantNumeric: 'tabular-nums',
        lineHeight: 1,
        color: trendColor,
      }}>
        {insight.value}
      </div>

      {/* divider */}
      <div style={{ height: 1, background: 'var(--color-kumo-line)' }} />

      {/* detail */}
      <p style={{ fontSize: 13, color: 'var(--text-color-kumo-subtle)', margin: 0, lineHeight: 1.65, opacity: 0.8 }}>
        {insight.detail}
      </p>
    </div>
  )
}

export default function InsightsPage() {
  return (
    <DashboardLayout>
      <TabBar />
      <div style={{ maxWidth: 1100, margin: '0 auto', padding: 'clamp(0.75rem,4vw,2rem)', width: '100%' }}>

        {/* header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16, marginBottom: 8 }}>
          <div>
            <h1 style={{ fontSize: 'clamp(1.1rem,4vw,1.25rem)', fontWeight: 500, color: 'var(--text-color-kumo-default)', margin: 0 }}>AI Insights</h1>
            <p style={{ fontSize: 13, color: 'var(--text-color-kumo-subtle)', marginTop: 5, marginBottom: 0 }}>
              AI-generated observations about your usage, performance, and spend.
            </p>
          </div>
          <div style={{
            display: 'inline-flex', alignItems: 'center', gap: 5,
            height: 28, padding: '0 10px', borderRadius: 6,
            fontSize: 12, fontWeight: 400,
            background: 'var(--color-kumo-tint)',
            border: '1px solid var(--color-kumo-line)',
            color: 'var(--text-color-kumo-subtle)',
            flexShrink: 0,
          }}>
            <span style={{ width: 5, height: 5, borderRadius: '50%', background: 'var(--text-color-kumo-subtle)', opacity: 0.5, flexShrink: 0 }} />
            AI-generated
          </div>
        </div>

        <div style={{ height: 1, background: 'var(--color-kumo-line)', margin: '20px 0 24px' }} />

        {/* grid */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 10 }}>
          {INSIGHTS.map((ins, i) => <InsightCard key={i} insight={ins} />)}
        </div>

        {/* footer note */}
        <p style={{
          marginTop: 24, fontSize: 12,
          color: 'var(--text-color-kumo-subtle)',
          opacity: 0.6, lineHeight: 1.6,
        }}>
          Insights are generated automatically based on your last 30 days of analytics data. They refresh daily at midnight UTC.
        </p>

      </div>
    </DashboardLayout>
  )
}
